// <auto-generated />
using System;
using InventoryAlert.Infrastructure.Persistence.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryAlert.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414042036_RefactorToFinanceV2")]
    partial class RefactorToFinanceV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("TriggerOnce")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TickerSymbol", "IsActive");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.EarningsSurprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ActualEps")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimateEps")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReportDate")
                        .HasColumnType("date");

                    b.Property<double?>("SurprisePercent")
                        .HasColumnType("double precision");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("TickerSymbol", "Period")
                        .IsUnique();

                    b.ToTable("earnings_surprises", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.InsiderTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("FilingDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("Share")
                        .HasColumnType("bigint");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TickerSymbol", "TransactionDate");

                    b.ToTable("insider_transactions", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlertRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TickerSymbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.PriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Open")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrevClose")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("TickerSymbol", "RecordedAt");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.RecommendationTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Buy")
                        .HasColumnType("integer");

                    b.Property<int>("Hold")
                        .HasColumnType("integer");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sell")
                        .HasColumnType("integer");

                    b.Property<int>("StrongBuy")
                        .HasColumnType("integer");

                    b.Property<int>("StrongSell")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("TickerSymbol", "Period")
                        .IsUnique();

                    b.ToTable("recommendation_trends", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.StockListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("Ipo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastProfileSync")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Logo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("TickerSymbol")
                        .IsUnique();

                    b.ToTable("stock_listings", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.StockMetric", b =>
                {
                    b.Property<string>("TickerSymbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("DividendYield")
                        .HasColumnType("double precision");

                    b.Property<double?>("EpsBasicTtm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MarginNet")
                        .HasColumnType("double precision");

                    b.Property<double?>("PbRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("PeRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("RevenueGrowthTtm")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Week52High")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Week52Low")
                        .HasColumnType("numeric");

                    b.HasKey("TickerSymbol");

                    b.ToTable("stock_metrics", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("TradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TickerSymbol");

                    b.HasIndex("UserId", "TickerSymbol", "TradedAt");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.WatchlistItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TickerSymbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "TickerSymbol");

                    b.HasIndex("TickerSymbol");

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.AlertRule", b =>
                {
                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.StockListing", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.EarningsSurprise", b =>
                {
                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.StockListing", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.InsiderTransaction", b =>
                {
                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.StockListing", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.Notification", b =>
                {
                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.AlertRule", null)
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.RecommendationTrend", b =>
                {
                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.StockListing", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.StockMetric", b =>
                {
                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.StockListing", null)
                        .WithOne()
                        .HasForeignKey("InventoryAlert.Domain.Entities.Postgres.StockMetric", "TickerSymbol")
                        .HasPrincipalKey("InventoryAlert.Domain.Entities.Postgres.StockListing", "TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.Trade", b =>
                {
                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.StockListing", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryAlert.Domain.Entities.Postgres.WatchlistItem", b =>
                {
                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.StockListing", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryAlert.Domain.Entities.Postgres.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
