// <auto-generated />
using System;
using InventoryAlert.Contracts.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryAlert.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260407161329_BigUpdateDb")]
    partial class BigUpdateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryAlert.Contracts.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotifyChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_alertrules_symbol");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_alertrules_user");

                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Contracts.Entities.CompanyProfile", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("IpoDate")
                        .HasColumnType("date");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebUrl")
                        .HasColumnType("text");

                    b.HasKey("Symbol");

                    b.ToTable("CompanyProfiles", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Contracts.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("LastAlertSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("OriginPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<double>("PriceAlertThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("StockAlertThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("StockCount")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentPrice = 200m,
                            Name = "Apple",
                            OriginPrice = 250m,
                            PriceAlertThreshold = 0.20000000000000001,
                            StockAlertThreshold = 0,
                            StockCount = 50,
                            TickerSymbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CurrentPrice = 300m,
                            Name = "Google",
                            OriginPrice = 300m,
                            PriceAlertThreshold = 0.10000000000000001,
                            StockAlertThreshold = 0,
                            StockCount = 100,
                            TickerSymbol = "GOOGL"
                        },
                        new
                        {
                            Id = 3,
                            CurrentPrice = 400m,
                            Name = "Microsoft",
                            OriginPrice = 400m,
                            PriceAlertThreshold = 0.14999999999999999,
                            StockAlertThreshold = 0,
                            StockCount = 5,
                            TickerSymbol = "MSFT"
                        });
                });

            modelBuilder.Entity("InventoryAlert.Contracts.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Contracts.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_watchlists_user");

                    b.HasIndex("UserId", "Symbol")
                        .IsUnique();

                    b.ToTable("Watchlists", (string)null);
                });

            modelBuilder.Entity("InventoryAlert.Contracts.Entities.Watchlist", b =>
                {
                    b.HasOne("InventoryAlert.Contracts.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
