// <auto-generated />
using System;
using InventoryAlert.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryAlert.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403171231_updateSeedDataApple")]
    partial class updateSeedDataApple
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryAlert.Api.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastAlertSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("OriginPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("PriceAlertThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<int>("StockCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TickerSymbol")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentPrice = 200m,
                            Name = "Apple",
                            OriginPrice = 250m,
                            PriceAlertThreshold = 0.20000000000000001,
                            StockCount = 50,
                            TickerSymbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CurrentPrice = 300m,
                            Name = "Google",
                            OriginPrice = 300m,
                            PriceAlertThreshold = 0.10000000000000001,
                            StockCount = 100,
                            TickerSymbol = "GOOGL"
                        },
                        new
                        {
                            Id = 3,
                            CurrentPrice = 400m,
                            Name = "Microsoft",
                            OriginPrice = 400m,
                            PriceAlertThreshold = 0.14999999999999999,
                            StockCount = 5,
                            TickerSymbol = "MSFT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
