// <auto-generated />
using System;
using InventoryAlert.Contracts.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryAlert.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryAlert.Contracts.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("LastAlertSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("OriginPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<double>("PriceAlertThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("StockAlertThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("StockCount")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentPrice = 200m,
                            Name = "Apple",
                            OriginPrice = 250m,
                            PriceAlertThreshold = 0.20000000000000001,
                            StockAlertThreshold = 0,
                            StockCount = 50,
                            TickerSymbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CurrentPrice = 300m,
                            Name = "Google",
                            OriginPrice = 300m,
                            PriceAlertThreshold = 0.10000000000000001,
                            StockAlertThreshold = 0,
                            StockCount = 100,
                            TickerSymbol = "GOOGL"
                        },
                        new
                        {
                            Id = 3,
                            CurrentPrice = 400m,
                            Name = "Microsoft",
                            OriginPrice = 400m,
                            PriceAlertThreshold = 0.14999999999999999,
                            StockAlertThreshold = 0,
                            StockCount = 5,
                            TickerSymbol = "MSFT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
