name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: Restore dependencies
      run: dotnet restore InventoryManagementSystem/InventoryManagementSystem.sln
      
    - name: Build
      run: dotnet build InventoryManagementSystem/InventoryManagementSystem.sln --no-restore --configuration Release

    - name: Architecture Test
      run: dotnet test InventoryManagementSystem/InventoryAlert.ArchitectureTests/InventoryAlert.ArchitectureTests.csproj --no-restore --no-build --configuration Release --verbosity normal
      
    - name: Unit Test
      run: dotnet test InventoryManagementSystem/InventoryAlert.UnitTests/InventoryAlert.UnitTests.csproj --no-restore --no-build --configuration Release --verbosity normal
